export const GET_ALL_CASES_START = 'GET_ALL_CASES_START'
export const GET_ALL_CASES = 'GET_ALL_CASES'
export const GET_ALL_CASES_STOP = 'GET_ALL_CASES_STOP'

export const GET_ALL_COUNTRIES_START = 'GET_ALL_COUNTRIES_START'
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const GET_ALL_COUNTRIES_STOP = 'GET_ALL_COUNTRIES_STOP'

export const GET_COUNTRIES_START = 'GET_COUNTRIES_START'
export const GET_COUNTRIES = 'GET_COUNTRIES'
export const GET_COUNTRIES_STOP = 'GET_COUNTRIES_STOP'

export const baseURL = 'https://coronavirus-19-api.herokuapp.com/'